# used to install machines and if no coreos 
# version is given in the profile
default_coreos_version: 1068.6.0

network:
  pxe: true
  interface: eth1
  bind_addr: 192.168.2.2
  bootstrap_range:
    start: 192.168.2.10
    end: 192.168.2.20
  ip_range:
    start: 192.168.2.21
    end: 192.168.2.30
  dns: [8.8.8.8, 8.8.4.4]
  router: 192.168.2.2
  network_model: singlenic

profiles:
  - name: core-services
    quantity: 3
    tags:
      - "role-core=true"
    coreos_version: "1068.6.0"
  - name: default
    disable_engine: true
    coreos_version: "835.13.0"
    tags:
      - "role-worker=true"
      - "stack-compute=true"

templates_env:
  ssh_authorized_keys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
  mayu_http_endpoint: "http://192.168.2.2:4080"
  yochu_localsubnet: "192.168.2.0/24"
  yochu_gateway: "192.168.2.2/32"
  yochu_private_registry: "registry.private.tiny.swarm"
  yochu_http_endpoint: "http://192.168.2.2:4080/yochu"
  yochu_version: 0.19.1
  etcd_version: v2.2.5-gs-1
  fleet_version: v0.11.5-gs-grpc-1
  docker_version: 1.10.3
  rkt_version: v1.3.0
  k8s_version: v1.2.2
